# Generated by Django 5.0.6 on 2026-05-28 17:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL')], max_length=50)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('processing_status', models.CharField(default='PENDING', max_length=50)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEmissionRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('scope', models.CharField(choices=[('SCOPE1', 'Scope 1'), ('SCOPE2', 'Scope 2'), ('SCOPE3', 'Scope 3')], max_length=50)),
                ('activity_type', models.CharField(max_length=255)),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('raw_value', models.FloatField()),
                ('normalized_value', models.FloatField()),
                ('emission_factor', models.FloatField(default=0)),
                ('emission_kg_co2e', models.FloatField(default=0)),
                ('record_date', models.DateField()),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('anomaly_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ingestion.tenant')),
                ('uploaded_file', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ingestion.uploadedfile')),
            ],
            options={
                'verbose_name': 'historical emission record',
                'verbose_name_plural': 'historical emission records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('scope', models.CharField(choices=[('SCOPE1', 'Scope 1'), ('SCOPE2', 'Scope 2'), ('SCOPE3', 'Scope 3')], max_length=50)),
                ('activity_type', models.CharField(max_length=255)),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('raw_value', models.FloatField()),
                ('normalized_value', models.FloatField()),
                ('emission_factor', models.FloatField(default=0)),
                ('emission_kg_co2e', models.FloatField(default=0)),
                ('record_date', models.DateField()),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('anomaly_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.tenant')),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.uploadedfile')),
            ],
        ),
    ]
